quiz/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/requests/update/:id' => 'requests#index', as: :update_request
  post "/requests/:search" => "requests#index", as: :search_request


  resources :requests

  root 'requests#index'


end

quiz/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

quiz/app/models/request.rb
class Request < ApplicationRecord
  paginates_per 7
  # before_action :find_request, only: [:show, :edit, :update, :destroy]
  validates :name, presence: true
  validates :email, presence: true

  after_initialize do |request|
    request.completed ||= false
  end

  def self.search(query)
    if (query)
      where(["name LIKE ? OR email LIKE ? OR department LIKE ? OR message LIKE ? ", "%#{query}", "%#{query}", "%#{query}", "%#{query}"])
    else
      all
    end
  end


end

quiz/app/models/support.rb
class Support < ApplicationRecord
end

quiz/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

quiz/app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :find_request, only: [:show, :edit, :update, :destroy]
  def new
    @request = Request.new
  end

  def create
  request_params = params.require(:request).permit(:name, :email, :department, :message)
  @request = Request.new request_params
    if @request.save
      redirect_to request_path(@request)
      flash[:notice] = "Supprt request created!"
    else
      flash[:alert] = "Support request could not be created."
      render (:new)
    end
  end

  def show
  end

  def index
    if params[:search_item]
       @search_item = params[:search_item]
       @requests = Request.where(["name ILIKE ? OR email ILIKE ? OR department ILIKE ? OR message ILIKE ?", "%#{@search_item}%","%#{@search_item}%","%#{@search_item}%","%#{@search_item}%"]).page(params[:page])
     else
       #@requests = Request.order(created_at: :desc).page(params[:page])
       @requests = Request.order("id DESC").page(params[:page])
     end

  if params[:id]
    @request = Request.find params[:id]
    @request.status == false ? @request.status = true : @request.status = false
    @request.save
  end


  end

  def update
    request_params = params.require(:request).permit(:name, :email, :department, :message, :completed)
    @request       = Request.find params[:id]
    if @request.update request_params
      redirect_to request_path(@request)
    else
      render :edit
    end
  end

  def destroy
    @request.destroy
    redirect_to requests_path
    flash[:alert] = "Support Request deleted!"
  end

  # def self.search(keyword)
  #   where("name || email || department || message ILIKE ?","%#{keyword}%")
  # end


  private

def find_request
  @request = Request.find params[:id]
end

def request_params
  params.require(:request).permit(:name, :email, :department, :message)
end





end

quiz/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

  def thankyou
    @name = params[:name]
  end

end

quiz/app/helpers/application_helper.rb
module ApplicationHelper
end

quiz/app/helpers/requests_helper.rb
module RequestsHelper
end

quiz/app/helpers/welcome_helper.rb
module WelcomeHelper
end

quiz/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Supporter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "All Support Requests", root_path %>
    |
    <%= link_to "New Support Requests", new_request_path  %>
    |
    <hr>
    <%= yield %>
  </body>
</html>

quiz/app/views/requests/_form.html.erb
<% if @request.errors.any? %>
  <ul>
    <% @request.errors.full_message.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @request do |f| %>
<div>
  <%= f.label :name %>
  <%= f.text_area :name %>
</div>
<div>
  <%= f.label :email %>
  <%= f.text_area :email %>
</div>
<%= f.label :department, "Department" %>
<%= f.radio_button :department, "Sales" %>
<%= f.label:dep_sales, "Sales" %>
<%= f.radio_button :department, "Marketing" %>
<%= f.label :dept_marketing, "Marketing" %>
<%= f.radio_button :department, "Technical" %>
<%= f.label :dept_technical, "Technical" %>

<div>
  <%= f.label :message %></br>
  <%= f.text_area :message %>
</div>
<%= f.submit %>

<% end %>

quiz/app/views/requests/edit.html.erb
<h1>Edit a Support Request</h1>

<%= render "form" %>

quiz/app/views/requests/index.html.erb
<h1>All Support Requests</h1>
<%= form_tag search_request_path(:search) do %>
 <%= text_area_tag :search_item %>
 <%= submit_tag "Search" %>
<% end %>


<% if @requests != nil %>

<table class="table table-striped">
  <thead>
    <th>Name</th>
    <th>Email</th>
    <th>Department</th>
    <th>Message</th>
  </thead>
  <tbody>

  <% @requests.each do |x| %>
    <tr>
      <td><%= x.name %></td>
      <td><%= x.email %></td>
      <td><%= x.department %></td>
      <td><%= x.message %></td>
      <td>
        <%= link_to "View", request_path(x) %>
        <%= link_to "Edit", edit_request_path(x) %>
        <%= link_to "Delete", request_path(x), method: :delete, data: {confirm: "Are you sure you want to delete this support request?"} %>
        <% if x.status == false %>
        <%= link_to "Not Done", update_request_path(x), class: "btn not-done"%>
        <% else %>
        <%= link_to "Done", update_request_path(x), class: "btn done"%>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<% else %>
<% end %>

<%= paginate @requests %>

quiz/app/views/requests/new.html.erb
<h1>Supporter</h1>

<%= render "form" %>

quiz/app/views/requests/show.html.erb
<h2>View Support Request</h2>

<p><strong>Name:</strong> <%= @request.name %><br>
   <strong>Email:</strong> <%= @request.email %><br>
   <strong>Department:</strong> <%= @request.department %>
</p>
<p><strong>Message:</strong> <%= @request.message %></p>

quiz/app/views/welcome/index.html.erb
<h1>Supporter</h1>

quiz/app/views/welcome/thankyou.html.erb
<h1>Thank You <%= @name %></h1>